gitea test

diff --git a/.github/workflows/dailyshow-daily-schedule.yml b/.github/workflows/dailyshow-daily-schedule.yml
--- a/.github/workflows/dailyshow-daily-schedule.yml
+++ b/.github/workflows/dailyshow-daily-schedule.yml
@@ -16,12 +16,26 @@ jobs:
     steps:
       - name: Login to Tencent Cloud Container Registry
         run: |
-          docker login ccr.ccs.tencentyun.com -u ${{ secrets.TENCENT_CLOUD_USERNAME }} -p ${{ secrets.TENCENT_CLOUD_PASSWORD }}
+          count=0
+          while true; do
+            docker login ccr.ccs.tencentyun.com -u ${{ secrets.TENCENT_CLOUD_USERNAME }} -p ${{ secrets.TENCENT_CLOUD_PASSWORD }}
+            docker pull ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker
+            if [ $? -eq 0 ]; then
+              break
+            fi
+            count=$((count+1))
+            if [ $count -gt 5 ]; then
+              echo "Failed to login to Tencent Cloud Container Registry after 5 attempts"
+              exit 1
+            fi
+            sleep 10
+          done
       
       - name: Run Docker container
         run: |
           lsmem
           lscpu
+          export default_vender=siliconflow
           export YOUTUBE_LINK="https://www.youtube.com/@TheDailyShow/videos"  
           export publish_title_prefix="【Daily Show】`date '+%Y.%m.%d'`-"
           docker run -e default_vender=$default_vender -e YOUTUBE_LINK="$YOUTUBE_LINK" -e episode_number=1 -e publish_title_prefix="$publish_title_prefix" ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker 
diff --git a/.github/workflows/dispatch.yml b/.github/workflows/dispatch.yml
--- a/.github/workflows/dispatch.yml
+++ b/.github/workflows/dispatch.yml
@@ -2,14 +2,10 @@ name: Manual Trigger
 on:
   workflow_dispatch:
     inputs:
-      default_vender:
-        description: 'Openai供应商 aliyun/glm/siliconflow'
-        required: true
-        default: 'glm'
       YOUTUBE_LINK:
         description: 'youtube地址'
         required: false
-        default: 'https://www.youtube.com/@wsj/videos'
+        default: 'https://www.youtube.com/playlist?list=PL6XRrncXkMaWWFyjMtzWWSeOocFr-N_3s'
       episode_number:
         description: '集数'
         required: true
@@ -21,7 +17,20 @@ jobs:
     steps:
       - name: Login to Tencent Cloud Container Registry
         run: |
-          docker login ccr.ccs.tencentyun.com -u ${{ secrets.TENCENT_CLOUD_USERNAME }} -p ${{ secrets.TENCENT_CLOUD_PASSWORD }}
+          count=0
+          while true; do
+            docker login ccr.ccs.tencentyun.com -u ${{ secrets.TENCENT_CLOUD_USERNAME }} -p ${{ secrets.TENCENT_CLOUD_PASSWORD }}
+            docker pull ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker
+            if [ $? -eq 0 ]; then
+              break
+            fi
+            count=$((count+1))
+            if [ $count -gt 5 ]; then
+              echo "Failed to login to Tencent Cloud Container Registry after 5 attempts"
+              exit 1
+            fi
+            sleep 10
+          done
       
       - name: Run Video Cut
         run: |
@@ -33,5 +42,7 @@ jobs:
           export default_vender=${{ github.event.inputs.default_vender }}
           export YOUTUBE_LINK="${{ github.event.inputs.YOUTUBE_LINK }}"
           export episode_number=${{ github.event.inputs.episode_number }}
-
+          if [ -z "$default_vender" ]; then
+            export default_vender=aliyun
+          fi
           docker run -e default_vender=$default_vender -e YOUTUBE_LINK="$YOUTUBE_LINK" -e episode_number=$episode_number ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker 
